import type { Merchant, PlatformMetrics } from '@/types';

export const merchants: Merchant[] = [
  {
    id: 'm1',
    name: 'Sakura Sushi',
    category: 'restaurant',
    cuisine: 'Japanese',
    location: 'Wudaokou Shopping Center, 2F',
    coordinates: { lat: 39.9928, lng: 116.3467 },
    rating: 4.6,
    priceRange: 'moderate',
    capacity: 48,
    privateRooms: true,
    features: ['sushi', 'sake', 'omakase', 'private room', 'counter seating'],
    currentStatus: {
      seatAvailability: 65,
      kitchenLoad: 45,
      queueTime: 15,
      inventoryLevel: 80,
      isAcceptingOrders: true,
    },
    metrics: {
      fulfillmentRate: 94,
      avgServiceTime: 75,
      customerSatisfaction: 4.5,
      totalContracts: 287,
      breachRate: 2.1,
    },
  },
  {
    id: 'm2',
    name: 'Spice Garden',
    category: 'restaurant',
    cuisine: 'Sichuan',
    location: 'Chengfu Road, No. 15',
    coordinates: { lat: 39.9912, lng: 116.3402 },
    rating: 4.4,
    priceRange: 'moderate',
    capacity: 36,
    privateRooms: true,
    features: ['spicy', 'hotpot', 'private room', 'group dining'],
    currentStatus: {
      seatAvailability: 40,
      kitchenLoad: 70,
      queueTime: 25,
      inventoryLevel: 65,
      isAcceptingOrders: true,
    },
    metrics: {
      fulfillmentRate: 89,
      avgServiceTime: 90,
      customerSatisfaction: 4.3,
      totalContracts: 203,
      breachRate: 4.5,
    },
  },
  {
    id: 'm3',
    name: 'Café de Flore',
    category: 'cafe',
    cuisine: 'French',
    location: 'Wudaokou Plaza, 1F',
    coordinates: { lat: 39.9935, lng: 116.3458 },
    rating: 4.7,
    priceRange: 'premium',
    capacity: 24,
    privateRooms: false,
    features: ['coffee', 'brunch', 'wifi', 'quiet', 'outdoor seating'],
    currentStatus: {
      seatAvailability: 80,
      kitchenLoad: 30,
      queueTime: 5,
      inventoryLevel: 90,
      isAcceptingOrders: true,
    },
    metrics: {
      fulfillmentRate: 97,
      avgServiceTime: 45,
      customerSatisfaction: 4.7,
      totalContracts: 412,
      breachRate: 0.8,
    },
  },
  {
    id: 'm4',
    name: 'Dragon Palace',
    category: 'restaurant',
    cuisine: 'Cantonese',
    location: 'Xueyuan Road, No. 8',
    coordinates: { lat: 39.9895, lng: 116.3445 },
    rating: 4.5,
    priceRange: 'premium',
    capacity: 60,
    privateRooms: true,
    features: ['dim sum', 'banquet', 'private room', 'business dining', 'parking'],
    currentStatus: {
      seatAvailability: 55,
      kitchenLoad: 60,
      queueTime: 20,
      inventoryLevel: 75,
      isAcceptingOrders: true,
    },
    metrics: {
      fulfillmentRate: 92,
      avgServiceTime: 90,
      customerSatisfaction: 4.4,
      totalContracts: 345,
      breachRate: 3.2,
    },
  },
  {
    id: 'm5',
    name: 'The Cozy Noodle',
    category: 'restaurant',
    cuisine: 'Chinese',
    location: 'Wudaokou Metro Station, B1',
    coordinates: { lat: 39.9942, lng: 116.3473 },
    rating: 4.2,
    priceRange: 'budget',
    capacity: 32,
    privateRooms: false,
    features: ['noodles', 'quick service', 'takeout'],
    currentStatus: {
      seatAvailability: 70,
      kitchenLoad: 55,
      queueTime: 10,
      inventoryLevel: 85,
      isAcceptingOrders: true,
    },
    metrics: {
      fulfillmentRate: 96,
      avgServiceTime: 30,
      customerSatisfaction: 4.1,
      totalContracts: 523,
      breachRate: 1.5,
    },
  },
  {
    id: 'm6',
    name: 'Mediterranean Breeze',
    category: 'restaurant',
    cuisine: 'Mediterranean',
    location: 'Zhongguancun Street, No. 28',
    coordinates: { lat: 39.9878, lng: 116.3421 },
    rating: 4.6,
    priceRange: 'moderate',
    capacity: 40,
    privateRooms: true,
    features: ['seafood', 'wine', 'private room', 'romantic', 'outdoor terrace'],
    currentStatus: {
      seatAvailability: 45,
      kitchenLoad: 65,
      queueTime: 18,
      inventoryLevel: 70,
      isAcceptingOrders: true,
    },
    metrics: {
      fulfillmentRate: 91,
      avgServiceTime: 85,
      customerSatisfaction: 4.5,
      totalContracts: 198,
      breachRate: 3.8,
    },
  },
  {
    id: 'm7',
    name: 'K-BBQ House',
    category: 'restaurant',
    cuisine: 'Korean',
    location: 'Wudaokou Shopping Center, 3F',
    coordinates: { lat: 39.9928, lng: 116.3467 },
    rating: 4.3,
    priceRange: 'moderate',
    capacity: 44,
    privateRooms: true,
    features: ['bbq', 'grill', 'private room', 'group dining', 'soju'],
    currentStatus: {
      seatAvailability: 35,
      kitchenLoad: 75,
      queueTime: 30,
      inventoryLevel: 60,
      isAcceptingOrders: true,
    },
    metrics: {
      fulfillmentRate: 87,
      avgServiceTime: 95,
      customerSatisfaction: 4.2,
      totalContracts: 267,
      breachRate: 5.2,
    },
  },
  {
    id: 'm8',
    name: 'Green Leaf Vegan',
    category: 'restaurant',
    cuisine: 'Vegetarian',
    location: 'Chengfu Road, No. 22',
    coordinates: { lat: 39.9908, lng: 116.3415 },
    rating: 4.8,
    priceRange: 'moderate',
    capacity: 28,
    privateRooms: false,
    features: ['vegan', 'organic', 'healthy', 'quiet', 'wifi'],
    currentStatus: {
      seatAvailability: 85,
      kitchenLoad: 25,
      queueTime: 0,
      inventoryLevel: 95,
      isAcceptingOrders: true,
    },
    metrics: {
      fulfillmentRate: 98,
      avgServiceTime: 50,
      customerSatisfaction: 4.8,
      totalContracts: 156,
      breachRate: 0.5,
    },
  },
  {
    id: 'm9',
    name: 'Night Owl Bar',
    category: 'bar',
    cuisine: 'International',
    location: 'Wudaokou Plaza, 2F',
    coordinates: { lat: 39.9935, lng: 116.3458 },
    rating: 4.4,
    priceRange: 'moderate',
    capacity: 80,
    privateRooms: true,
    features: ['cocktails', 'live music', 'private room', 'late night', 'dancing'],
    currentStatus: {
      seatAvailability: 50,
      kitchenLoad: 40,
      queueTime: 12,
      inventoryLevel: 88,
      isAcceptingOrders: true,
    },
    metrics: {
      fulfillmentRate: 93,
      avgServiceTime: 20,
      customerSatisfaction: 4.3,
      totalContracts: 389,
      breachRate: 2.8,
    },
  },
  {
    id: 'm10',
    name: 'Golden Dumpling',
    category: 'restaurant',
    cuisine: 'Chinese',
    location: 'Xueyuan Road, No. 12',
    coordinates: { lat: 39.9889, lng: 116.3438 },
    rating: 4.4,
    priceRange: 'budget',
    capacity: 36,
    privateRooms: false,
    features: ['dumplings', 'noodles', 'quick service', 'family friendly'],
    currentStatus: {
      seatAvailability: 60,
      kitchenLoad: 50,
      queueTime: 8,
      inventoryLevel: 90,
      isAcceptingOrders: true,
    },
    metrics: {
      fulfillmentRate: 95,
      avgServiceTime: 40,
      customerSatisfaction: 4.3,
      totalContracts: 445,
      breachRate: 1.8,
    },
  },
  {
    id: 'm11',
    name: 'Thai Orchid',
    category: 'restaurant',
    cuisine: 'Thai',
    location: 'Zhongguancun Street, No. 15',
    coordinates: { lat: 39.9865, lng: 116.3408 },
    rating: 4.5,
    priceRange: 'moderate',
    capacity: 32,
    privateRooms: true,
    features: ['thai curry', 'spicy', 'private room', 'vegetarian options'],
    currentStatus: {
      seatAvailability: 75,
      kitchenLoad: 45,
      queueTime: 10,
      inventoryLevel: 82,
      isAcceptingOrders: true,
    },
    metrics: {
      fulfillmentRate: 92,
      avgServiceTime: 65,
      customerSatisfaction: 4.4,
      totalContracts: 234,
      breachRate: 2.9,
    },
  },
  {
    id: 'm12',
    name: 'Pizza Corner',
    category: 'restaurant',
    cuisine: 'Italian',
    location: 'Wudaokou Shopping Center, 1F',
    coordinates: { lat: 39.9928, lng: 116.3467 },
    rating: 4.2,
    priceRange: 'budget',
    capacity: 40,
    privateRooms: false,
    features: ['pizza', 'pasta', 'delivery', 'family friendly', 'takeout'],
    currentStatus: {
      seatAvailability: 65,
      kitchenLoad: 55,
      queueTime: 12,
      inventoryLevel: 88,
      isAcceptingOrders: true,
    },
    metrics: {
      fulfillmentRate: 94,
      avgServiceTime: 35,
      customerSatisfaction: 4.1,
      totalContracts: 567,
      breachRate: 2.1,
    },
  },
];

export const platformMetrics: PlatformMetrics = {
  totalContracts: 4023,
  activeContracts: 156,
  conversionRate: 73.5,
  fulfillmentRate: 92.8,
  breachRate: 2.7,
  avgMatchScore: 84.2,
  totalUsers: 2847,
  totalMerchants: 156,
  revenueGenerated: 1256780,
  compensationPaid: 8950,
  contractsByDay: [
    { date: '2026-06-01', count: 145 },
    { date: '2026-06-02', count: 167 },
    { date: '2026-06-03', count: 189 },
    { date: '2026-06-04', count: 201 },
    { date: '2026-06-05', count: 178 },
    { date: '2026-06-06', count: 234 },
    { date: '2026-06-07', count: 156 },
  ],
  metricsByCategory: [
    { category: 'Japanese', contracts: 523, satisfaction: 4.5 },
    { category: 'Chinese', contracts: 892, satisfaction: 4.3 },
    { category: 'Korean', contracts: 367, satisfaction: 4.2 },
    { category: 'Thai', contracts: 234, satisfaction: 4.4 },
    { category: 'Italian', contracts: 567, satisfaction: 4.1 },
    { category: 'French', contracts: 412, satisfaction: 4.7 },
    { category: 'Mediterranean', contracts: 198, satisfaction: 4.5 },
    { category: 'Vegetarian', contracts: 156, satisfaction: 4.8 },
    { category: 'International', contracts: 389, satisfaction: 4.3 },
  ],
};

export const sampleDemands = [
  "Tonight 7pm, 4 people, budget 400, quiet, no spice, private room",
  "Tomorrow lunch, 2 people, want sushi near Wudaokou, budget 200 per person",
  "Friday evening, 6 people celebration, need private room, prefer Chinese cuisine",
  "Quick lunch for 1, budget 50, something light and healthy",
  "Date night, 2 people, romantic atmosphere, Western cuisine preferred",
];
